/**
 * Enhanced Decision Panel Component
 * Modular, engaging decision display with PDF export
 */

import React, { useState } from 'react';
import {
  Box,
  Typography,
  Grid,
  Card,
  CardContent,
  Button,
  Chip,
  Stack,
  Divider,
  IconButton,
  Collapse,
} from '@mui/material';
import { keyframes } from '@mui/system';
import type { Decision, CompanyData } from '../lib/types';
import ReactMarkdown from 'react-markdown';

// Icons
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CancelIcon from '@mui/icons-material/Cancel';
import HelpIcon from '@mui/icons-material/Help';
import DownloadIcon from '@mui/icons-material/Download';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';
import CalendarTodayIcon from '@mui/icons-material/CalendarToday';
import ArticleIcon from '@mui/icons-material/Article';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

interface DecisionPanelEnhancedProps {
  decision: Decision;
  companyData: CompanyData;
}

const fadeIn = keyframes`
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
`;

const pulse = keyframes`
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.05); }
`;

const DecisionPanelEnhanced: React.FC<DecisionPanelEnhancedProps> = ({ decision, companyData }) => {
  const [expandedMemo, setExpandedMemo] = useState(false);

  const getDecisionConfig = () => {
    switch (decision.decision) {
      case 'INVEST':
        return {
          icon: <CheckCircleIcon sx={{ fontSize: 80 }} />,
          color: '#10b981',
          label: 'INVEST',
          emoji: '🚀',
          title: 'Recommended Investment',
          subtitle: 'The council votes in favor of investment',
        };
      case 'MAYBE':
        return {
          icon: <HelpIcon sx={{ fontSize: 80 }} />,
          color: '#f59e0b',
          label: 'MAYBE',
          emoji: '🤔',
          title: 'Conditional Interest',
          subtitle: 'Further due diligence recommended',
        };
      case 'PASS':
        return {
          icon: <CancelIcon sx={{ fontSize: 80 }} />,
          color: '#ef4444',
          label: 'PASS',
          emoji: '⛔',
          title: 'Not Recommended',
          subtitle: 'The council votes against investment',
        };
    }
  };

  const config = getDecisionConfig();

  const handleDownloadPDF = () => {
    // Create a formatted text version for download
    const content = `
SOCRAT SPACE - INVESTMENT ANALYSIS
=====================================

Company: ${companyData.company_name}
Website: ${companyData.website}
Industry: ${companyData.industry}

DECISION: ${decision.decision}
=====================================

REASONING:
${decision.reasoning}

INVESTMENT MEMO:
${decision.investment_memo}

NEXT STEPS:
${decision.calendar_events?.map(event => `
- ${event.title}
  Date: ${event.start_time}
  Attendees: ${event.attendees.join(', ')}
  ${event.description}
`).join('\n') || 'No calendar events scheduled.'}

Generated by Socrat Space - AI Investment Intelligence
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${companyData.company_name.replace(/\s+/g, '_')}_Investment_Analysis.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Box sx={{ animation: `${fadeIn} 0.6s ease-out` }}>
      {/* Decision Header Card */}
      <Card
        sx={{
          mb: 3,
          background: `linear-gradient(135deg, ${config.color}15 0%, rgba(255,255,255,0.03) 100%)`,
          backdropFilter: 'blur(20px)',
          border: `2px solid ${config.color}40`,
          boxShadow: `0 8px 32px ${config.color}30`,
        }}
      >
        <CardContent sx={{ p: 4 }}>
          <Grid container spacing={3} alignItems="center">
            <Grid item xs={12} md={3} sx={{ textAlign: 'center' }}>
              <Box
                sx={{
                  display: 'inline-flex',
                  p: 3,
                  borderRadius: '50%',
                  background: `${config.color}20`,
                  border: `2px solid ${config.color}`,
                  color: config.color,
                  animation: `${pulse} 2s infinite`,
                  mb: 2,
                }}
              >
                {config.icon}
              </Box>
              <Typography variant="h3" sx={{ fontSize: '3rem' }}>
                {config.emoji}
              </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <Chip
                label={config.label}
                sx={{
                  background: config.color,
                  color: 'white',
                  fontWeight: 800,
                  fontSize: '1rem',
                  height: 40,
                  px: 2,
                  mb: 2,
                }}
              />
              <Typography
                variant="h3"
                sx={{
                  fontWeight: 800,
                  color: 'text.primary',
                  mb: 1,
                }}
              >
                {config.title}
              </Typography>
              <Typography
                variant="h6"
                sx={{
                  color: 'text.secondary',
                  fontWeight: 400,
                }}
              >
                {config.subtitle}
              </Typography>
            </Grid>
            <Grid item xs={12} md={3}>
              <Button
                variant="contained"
                startIcon={<DownloadIcon />}
                onClick={handleDownloadPDF}
                fullWidth
                sx={{
                  py: 1.5,
                  fontWeight: 600,
                  background: 'linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%)',
                  '&:hover': {
                    background: 'linear-gradient(135deg, #7c3aed 0%, #2563eb 100%)',
                  },
                }}
              >
                Export Report
              </Button>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      <Grid container spacing={3}>
        {/* Executive Summary */}
        <Grid item xs={12} lg={6}>
          <Card
            sx={{
              height: '100%',
              background: 'rgba(255, 255, 255, 0.03)',
              backdropFilter: 'blur(20px)',
              border: '1px solid rgba(255, 255, 255, 0.08)',
            }}
          >
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 2 }}>
                <Box
                  sx={{
                    width: 48,
                    height: 48,
                    borderRadius: 2,
                    background: 'linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  <TrendingUpIcon sx={{ color: 'white' }} />
                </Box>
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  Executive Summary
                </Typography>
              </Box>
              <Typography
                variant="body1"
                sx={{
                  color: 'text.primary',
                  lineHeight: 1.8,
                  whiteSpace: 'pre-wrap',
                }}
              >
                {decision.reasoning}
              </Typography>
            </CardContent>
          </Card>
        </Grid>

        {/* Next Steps */}
        {decision.calendar_events && decision.calendar_events.length > 0 && (
          <Grid item xs={12} lg={6}>
            <Card
              sx={{
                height: '100%',
                background: 'rgba(255, 255, 255, 0.03)',
                backdropFilter: 'blur(20px)',
                border: '1px solid rgba(255, 255, 255, 0.08)',
              }}
            >
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 2 }}>
                  <Box
                    sx={{
                      width: 48,
                      height: 48,
                      borderRadius: 2,
                      background: 'linear-gradient(135deg, #10b981 0%, #3b82f6 100%)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    <CalendarTodayIcon sx={{ color: 'white' }} />
                  </Box>
                  <Typography variant="h6" sx={{ fontWeight: 700 }}>
                    Next Steps
                  </Typography>
                </Box>
                <Stack spacing={2}>
                  {decision.calendar_events.map((event, index) => (
                    <Box
                      key={index}
                      sx={{
                        p: 2,
                        borderRadius: 2,
                        background: 'rgba(255, 255, 255, 0.03)',
                        border: '1px solid rgba(255, 255, 255, 0.05)',
                        transition: 'all 0.3s ease',
                        '&:hover': {
                          background: 'rgba(255, 255, 255, 0.05)',
                          borderColor: '#10b981',
                        },
                      }}
                    >
                      <Typography variant="subtitle1" sx={{ fontWeight: 600, mb: 0.5 }}>
                        {event.title}
                      </Typography>
                      <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mb: 1 }}>
                        {new Date(event.start_time).toLocaleString()}
                      </Typography>
                      <Typography variant="body2" sx={{ color: 'text.secondary', fontSize: '0.875rem' }}>
                        {event.description}
                      </Typography>
                      <Divider sx={{ my: 1, borderColor: 'rgba(255, 255, 255, 0.05)' }} />
                      <Typography variant="caption" sx={{ color: 'text.disabled' }}>
                        Attendees: {event.attendees.join(', ')}
                      </Typography>
                    </Box>
                  ))}
                </Stack>
              </CardContent>
            </Card>
          </Grid>
        )}

        {/* Investment Memo */}
        <Grid item xs={12}>
          <Card
            sx={{
              background: 'rgba(255, 255, 255, 0.03)',
              backdropFilter: 'blur(20px)',
              border: '1px solid rgba(255, 255, 255, 0.08)',
            }}
          >
            <CardContent>
              <Box
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  mb: 2,
                }}
              >
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                  <Box
                    sx={{
                      width: 48,
                      height: 48,
                      borderRadius: 2,
                      background: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    <ArticleIcon sx={{ color: 'white' }} />
                  </Box>
                  <Typography variant="h6" sx={{ fontWeight: 700 }}>
                    Investment Memo
                  </Typography>
                </Box>
                <IconButton
                  onClick={() => setExpandedMemo(!expandedMemo)}
                  sx={{
                    transform: expandedMemo ? 'rotate(180deg)' : 'rotate(0deg)',
                    transition: 'transform 0.3s',
                  }}
                >
                  <ExpandMoreIcon />
                </IconButton>
              </Box>

              <Collapse in={expandedMemo} timeout="auto">
                <Box
                  sx={{
                    p: 3,
                    borderRadius: 2,
                    background: 'rgba(0, 0, 0, 0.2)',
                    '& h1, & h2, & h3': {
                      color: 'text.primary',
                      fontWeight: 700,
                      mt: 2,
                      mb: 1,
                    },
                    '& p': {
                      color: 'text.primary',
                      lineHeight: 1.8,
                      mb: 1.5,
                    },
                    '& ul, & ol': {
                      color: 'text.primary',
                      pl: 3,
                    },
                    '& li': {
                      mb: 0.5,
                    },
                    '& code': {
                      background: 'rgba(255, 255, 255, 0.1)',
                      padding: '2px 6px',
                      borderRadius: 1,
                      fontSize: '0.875rem',
                    },
                    '& strong': {
                      color: '#8b5cf6',
                      fontWeight: 700,
                    },
                  }}
                >
                  <ReactMarkdown>{decision.investment_memo}</ReactMarkdown>
                </Box>
              </Collapse>

              {!expandedMemo && (
                <Typography
                  variant="body2"
                  sx={{
                    color: 'text.secondary',
                    fontStyle: 'italic',
                  }}
                >
                  Click to expand full investment memo with detailed analysis...
                </Typography>
              )}
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default DecisionPanelEnhanced;

